baseURL = "https://digitalkosovski.github.io/"
languageCode = "en-us"
title = "Agustín Cosovschi"
theme = "terminal"



[params]
  # This changes the big logo text
  [params.logo]
    text = "Agustín Cosovschi"
    # optional: ASCII-style or plain
    ascii = false
relativeURLs = true
